version: '3.8'

networks:
  testApp:
    # driver: bridge

volumes:
  ApplicationSql:

services:
  application:
    container_name: blog
    build:
      context: .
      dockerfile: Blog/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - testApp
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Helia@20794"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - testApp
    volumes:
      - ApplicationSql:/var/opt/mssql
